### PR TITLE
Fixes #128

### LINKED ISSUE #128: CEM with n_eval>1 causes crash for varying path lengths
CEM with n_eval>1 causes crash for varying path lengths, which e.g. for Hopper happens frequently.

I'll write a fix that calcs mean and stderr over return paths of varying lengths.

### PR DESCRIPTION
**Pull request by sytham**
Fixes #128

### CODE REVIEW

**Comment by dementrock** [comment]
Any reason to pad with -1e6 specifically? Sometimes shorter trajectories may be better than longer ones and this choice seems artificial.

**Comment by sytham** [comment]
The padded values are used as markers for np.ma.MaskedArray to apply the mask to, so they can be any value that does not occur in the original, unmasked array. To pad with None would have been better but that crashes np.ma.MaskedArray.std(). I chose -1e6 since surely that value will not occur in the path of discounted returns.

**Comment by dementrock** [comment]
I see. What about using np.nanmean?

**Comment by sytham** [comment]
That works as well and is better, thanks! Added the commit

**Pull request merged**
